import { z } from 'zod';

const brandInfoSchema = z.object({
  name: z.string(),
  tagline: z.string().optional(),
  logoUrl: z.string().optional(),
  primaryColor: z.string().optional(),
  accentColor: z.string().optional(),
  websiteUrl: z.string().optional(),
});

const productInfoSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  originalPrice: z.string().optional(),
  price: z.string().optional(),
  discount: z.string().optional(),
  features: z.array(z.string()).max(4).optional(),
  imageUrl: z.string().optional(),
});

const ctaSchema = z.object({
  text: z.string(),
  url: z.string().optional(),
  subtext: z.string().optional(),
});

/**
 * Shared Zod schema for all Remotion template compositions.
 *
 * Every template consumes the same `VideoContent` data model:
 *   brand, product, cta, backgroundImageUrl, headline, bodyText.
 * Adding a new template does NOT require a new schema — just a
 * new composition that renders this data differently.
 */
export const videoContentSchema = z.object({
  brand: brandInfoSchema,
  product: productInfoSchema,
  cta: ctaSchema,
  backgroundImageUrl: z.string().optional(),
  headline: z.string().optional(),
  bodyText: z.string().optional(),
  /** Optional data-explainer fields. Existing templates safely ignore these. */
  title: z.string().optional(),
  subtitle: z.string().optional(),
  statistic: z.number().finite().optional(),
  percentage: z.number().finite().optional(),
  chartData: z.array(z.number().finite()).optional(),
  labels: z.array(z.string()).optional(),
  source: z.string().optional(),
  /** Optional broadcast-news fields. Existing templates safely ignore these. */
  category: z.string().optional(),
  location: z.string().optional(),
  date: z.string().optional(),
  image: z.string().optional(),
  tickerText: z.string().optional(),
  /** Optional countdown fields. Existing templates safely ignore these. */
  listTitle: z.string().optional(),
  item1Title: z.string().optional(),
  item1Description: z.string().optional(),
  item1Image: z.string().optional(),
  item1AccentText: z.string().optional(),
  item2Title: z.string().optional(),
  item2Description: z.string().optional(),
  item2Image: z.string().optional(),
  item2AccentText: z.string().optional(),
  item3Title: z.string().optional(),
  item3Description: z.string().optional(),
  item3Image: z.string().optional(),
  item3AccentText: z.string().optional(),
  item4Title: z.string().optional(),
  item4Description: z.string().optional(),
  item4Image: z.string().optional(),
  item4AccentText: z.string().optional(),
  item5Title: z.string().optional(),
  item5Description: z.string().optional(),
  item5Image: z.string().optional(),
  item5AccentText: z.string().optional(),
  /** Optional movie trailer fields. Existing templates safely ignore these. */
  description: z.string().optional(),
  statisticLabel: z.string().optional(),
  year: z.string().optional(),
  /** Optional YouTube template fields. Existing templates safely ignore these. */
  gamerTag: z.string().optional(),
  score: z.string().optional(),
  gameName: z.string().optional(),
  audioWaveformText: z.string().optional(),
  codeSnippet: z.string().optional(),
  versionBadge: z.string().optional(),
  locationStamp: z.string().optional(),
  seasonTag: z.string().optional(),
  marketTicker: z.string().optional(),
  growthStat: z.string().optional(),
  /** Optional event & masterclass fields. Existing templates safely ignore these. */
  speakerName: z.string().optional(),
  eventDate: z.string().optional(),
  /** Optional new YouTube templates fields. Existing templates safely ignore these. */
  thanksMessage: z.string().optional(),
  nextVideoTitle: z.string().optional(),
  recommendedVideoTitle: z.string().optional(),
  subscribersCount: z.string().optional(),
  techCategory: z.string().optional(),
  ratingScore: z.string().optional(),
  questionText: z.string().optional(),
  explanationText: z.string().optional(),
  options: z.array(z.string()).optional(),
  rankBadge: z.string().optional(),
  killStreakCount: z.string().optional(),
  gameTitle: z.string().optional(),
  podcastTitle: z.string().optional(),
  hostName: z.string().optional(),
  guestName: z.string().optional(),
  topicTagline: z.string().optional(),
  exerciseName: z.string().optional(),
  caloriesBurned: z.string().optional(),
  nextExerciseName: z.string().optional(),
  gpsCoordinates: z.string().optional(),
  altitudeMetres: z.string().optional(),
  filmTitle: z.string().optional(),
  cinematicTagline: z.string().optional(),
  commentatorName: z.string().optional(),
  commentatorTitle: z.string().optional(),
  topicChapterTag: z.string().optional(),
  sourceCitationText: z.string().optional(),
  trackTitle: z.string().optional(),
  artistName: z.string().optional(),
  streamSchedule: z.string().optional(),
  quoteText: z.string().optional(),
  quoteAuthor: z.string().optional(),
  keyMindsetPoint: z.string().optional(),
  recipeName: z.string().optional(),
  prepTime: z.string().optional(),
  servings: z.string().optional(),
  ingredientsList: z.array(z.string()).optional(),
  craftTitle: z.string().optional(),
  difficultyLevel: z.string().optional(),
  materialsNeeded: z.array(z.string()).optional(),
  stepCount: z.string().optional(),
  movieTitle: z.string().optional(),
  criticScore: z.string().optional(),
  audienceScore: z.string().optional(),
  verdictBadge: z.string().optional(),
  carModelName: z.string().optional(),
  accelerationStat: z.string().optional(),
  horsepowerStat: z.string().optional(),
  topSpeedStat: z.string().optional(),
  pairSymbol: z.string().optional(),
  entryTargetPrice: z.string().optional(),
  profitPercentage: z.string().optional(),
  leverageTag: z.string().optional(),
  repoName: z.string().optional(),
  githubStars: z.string().optional(),
  techStackTags: z.array(z.string()).optional(),
  terminalCommand: z.string().optional(),
  animeTitle: z.string().optional(),
  characterName: z.string().optional(),
  powerLevelScore: z.string().optional(),
  studioName: z.string().optional(),
  propertyName: z.string().optional(),
  propertyPriceTag: z.string().optional(),
  propertySpecs: z.array(z.string()).optional(),
  realtorContact: z.string().optional(),
  hackTitle: z.string().optional(),
  problemStatement: z.string().optional(),
  solutionHack: z.string().optional(),
  hackDifficulty: z.string().optional(),
  trendingTopic: z.string().optional(),
  viralCountText: z.string().optional(),
  socialPostSnippet: z.string().optional(),
  eraTimestamp: z.string().optional(),
  historicalEventName: z.string().optional(),
  historicalQuote: z.string().optional(),
  lookName: z.string().optional(),
  paletteColors: z.array(z.string()).optional(),
  discountCodeTag: z.string().optional(),
  soundTriggerName: z.string().optional(),
  binauralTag: z.string().optional(),
  ambientCategory: z.string().optional(),
  companyName: z.string().optional(),
  valuationStat: z.string().optional(),
  keyGrowthDrivers: z.array(z.string()).optional(),
  takeawayConclusion: z.string().optional(),
});

/** Input props type for every template composition. */
export type VideoContentProps = z.infer<typeof videoContentSchema>;
